=== redbass/recruitmentapp_core/resources/schemas/create_company.json
{
	"$schema": "http://json-schema.org/draft-07/schema#",
    "properties": {
        "name": { "type": "string", "minLength": 1, "maxLength": 50 },
        "description": { "type": "string", "minLength": 1, "maxLength": 500  },
        "vat": { "type": "string", "minLength": 1, "maxLength": 25  },
        "contacts":{
            "type": "object",
            "properties": {
                "address": {
                    "properties": {
                        "number": { "type": "string" },
                        "street": { "type": "string" },
                        "town": { "type": "string" },
                        "city": { "type": "string" },
                        "postcode": { "type": "string" },
                        "country": { "type": "string" }
                    },
                    "required": ["number", "street", "city", "postcode"],
                     "additionalProperties": false
                },
                "email": { "type": "string", "minLength": 1, "maxLength": 50 },
                "phone_number": { "type": "string", "minLength": 1, "maxLength": 25 }
            },
            "required": ["address", "email", "phone_number"],
            "additionalProperties": false
        },
        "metadata": {
            "type": "object",
            "properties": {
                "trades": {
                    "type": "array",
                    "minItems": 1,
                    "uniqueItems": true
                }
            },
            "required": ["trades"],
            "additionalProperties": false
        }
    },
     "required": ["name", "description", "vat", "contacts", "metadata"],
     "additionalProperties": false
}

=== redbass/recruitmentapp_core/resources/example_models/create_company_input.json
{
    "name": "The Name",
    "description": "this is a description",
    "vat": "123456",
    "contacts": {
        "address": {
            "number": "6 (1f1)",
            "street": "Drum Terrace",
            "city": "Edinburgh",
            "town": "Edinburgh",
            "postcode": "eh7 7gq",
            "country": "United Kingdom"
        },
        "email": "test@gma.il",
        "phone_number": "+44078735123"
    },
    "metadata": {
        "trades": [
            "trade 1",
            "trade 2"
        ]
    }
}
